channels:
  - conda-forge
dependencies:
  # Build dependencies
  - git
  - make
  - doxygen
  - python
  # Host dependencies
  - sphinx==4.5.0
  - docutils==0.17.1
  - pydata-sphinx-theme==0.13.3
  - sphinx-panels==0.6.0
  - sphinx-design==0.4.1
  - breathe==4.33.0
